apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
...
  template:
    metadata:
      labels:
...
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
