apiVersion: v1
kind: Pod
metadata:
  name: pre-install-1
  labels:
    name: pre-install-1
spec:
  containers:
  - name: pre-install-1
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 60 && echo first pre-install hook is done" ]
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pre-install-2
  labels:
    name: pre-install-2
spec:
  containers:
  - name: pre-install-2
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 60 && echo second pre-install hook is done" ]
  restartPolicy: Never
