---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        timestamp: {{ now }}       
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-html-volume
        configMap:
          name: index-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
###
